markdown: rdiscount
permalink: /:title/
url: http://www.99diary.com
name: 久久日记本
author: flyher
qq: 
email: slivery@icloud.com
duoshuo: flyher
beian: 暂无
cnzz: 1000524648
weibo: 
github: flyher
pygments: true
safe: true
paginate: 20
about: "这是flyher的测试博客"
