markdown: rdiscount
permalink: /:title/
url: http://99diary.com
name: 久久日记本
author: flyher
qq: 
email: slivery#icloud.com
#duoshuo: 99diary
beian: 暂无
cnzz: 1000524648
weibo: 
github: flyher
pygments: true
safe: true
paginate: 20
about: "这是flyher的测试博客

同时，你可以通过本域名访问所有的项目,例如：<br/>
[树莓派资源](http://99diary.com/shumeipai):树莓派资料;<br/>
[EmuchSign](http://99diary.com/EmuchSign)：小木虫签到;<br/>
[JqTimeLine](http://99diary.com/JqTimeLine):一个折线图的画法<br>
......

"

